# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
 vmImage: 'ubuntu-latest'

steps:
- checkout: self
  submodules: true
    
- bash: |
    sudo apt install -y hugo
    hugo --minify -d $(Build.ArtifactStagingDirectory)



- task: PublishPipelineArtifact@0
  displayName: 'Publish Hugo site as artifact'
  inputs:
    artifactName: 'hugo-site'
    targetPath: '$(Build.ArtifactStagingDirectory)'
