# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
 vmImage: 'windows-latest'

steps:
- checkout: self
  submodules: true
    
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)'
    publishLocation: 'pipeline'

- task: giuliovdev.hugo-extension.hugo-build-task-v2.HugoTask.HugoTask@1
  inputs:
    source: 
    destination: 'public'
    targetPath: '$(Build.ArtifactStagingDirectory)/public'
    